version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports: 
      - 80:80 
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    networks: 
      - backend
    depends_on:
      - postgres
  flipay:
    container_name: flipay
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    networks:
      - backend
    depends_on:
      - postgres
volumes:
  postgres-data:
    name: postgres-data

networks:
  backend: